version: '2'
services:
  freenet:
    container_name: freenet
    image: chrisbensch/docker-freenet
    network_mode: "host"
    ports:
      - "127.0.0.1:8888:8888"
      - "127.0.0.1:9481:9481"
      - "12345:12345/udp"
      - "12346:12346/udp"
    volumes:
      - ./conf/freenet:/conf
      - ./data/freenet:/data
    environment:
    - allowedhosts=127.0.0.1,0:0:0:0:0:0:0:1,192.168.0.0/24,10.10.10.0/24
    - darknetport=8675
    - opennetport=8676
